import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


// AWS Imports
import { Amplify } from '@/node_modules/aws-amplify/dist/esm/index';
import awsExports from '../src/aws-exports';

Amplify.configure({ ...awsExports, ssr: true })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quote Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
